import { z } from "zod";
import { withApplicationConnection } from "../../utils/ConnectionManager.js";
import type { DomainToolDefinition } from "../domainRuntime.js";

const GenericResponseSchema = z.object({}).passthrough();

const SuperelevationGetArgs = z.object({ action: z.literal("get"), alignmentName: z.string(), includeRawData: z.boolean().optional() });
const SuperelevationSetArgs = z.object({ action: z.literal("set"), alignmentName: z.string(), designSpeed: z.number().positive(), normalCrownSlope: z.number(), attainmentMethod: z.enum(["AASHTO_2001", "AASHTO_2011", "manual"]).optional(), pivotPoint: z.enum(["centerline", "inside_edge", "outside_edge"]).optional() });
const SuperelevationDesignCheckArgs = z.object({ action: z.literal("design_check"), alignmentName: z.string(), designSpeed: z.number().positive(), maxSuperelevation: z.number().positive(), checkAttainmentLength: z.boolean().optional(), checkRunoffLength: z.boolean().optional() });
const SuperelevationReportArgs = z.object({ action: z.literal("report"), alignmentName: z.string(), outputPath: z.string().optional(), overwrite: z.boolean().optional(), includeRunoffTable: z.boolean().optional(), includeViolations: z.boolean().optional() });

export const SUPERELEVATION_DOMAIN_DEFINITION: DomainToolDefinition = {
  domain: "alignment",
  actions: {
    get: { action: "get", inputSchema: SuperelevationGetArgs, responseSchema: GenericResponseSchema, capabilities: ["query", "inspect"], requiresActiveDrawing: true, safeForRetry: true, pluginMethods: ["getSuperelevation"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("getSuperelevation", { alignmentName: args.alignmentName, includeRawData: args.includeRawData ?? false })) },
    set: { action: "set", inputSchema: SuperelevationSetArgs, responseSchema: GenericResponseSchema, capabilities: ["edit"], requiresActiveDrawing: true, safeForRetry: false, pluginMethods: ["setSuperelevation"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("setSuperelevation", { alignmentName: args.alignmentName, designSpeed: args.designSpeed, normalCrownSlope: args.normalCrownSlope, attainmentMethod: args.attainmentMethod ?? "AASHTO_2011", pivotPoint: args.pivotPoint ?? "centerline" })) },
    design_check: { action: "design_check", inputSchema: SuperelevationDesignCheckArgs, responseSchema: GenericResponseSchema, capabilities: ["query", "analyze"], requiresActiveDrawing: true, safeForRetry: true, pluginMethods: ["checkSuperelevationDesign"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("checkSuperelevationDesign", { alignmentName: args.alignmentName, designSpeed: args.designSpeed, maxSuperelevation: args.maxSuperelevation, checkAttainmentLength: args.checkAttainmentLength ?? false, checkRunoffLength: args.checkRunoffLength ?? false })) },
    report: { action: "report", inputSchema: SuperelevationReportArgs, responseSchema: GenericResponseSchema, capabilities: ["query", "generate", "export"], requiresActiveDrawing: true, safeForRetry: false, pluginMethods: ["generateSuperelevationReport"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("generateSuperelevationReport", { alignmentName: args.alignmentName, outputPath: args.outputPath ?? null, overwrite: args.overwrite ?? false, includeRunoffTable: args.includeRunoffTable ?? true, includeViolations: args.includeViolations ?? false })) },
  },
  exposures: [
    { toolName: "civil3d_superelevation", displayName: "Civil 3D Superelevation", description: "Gets, sets, and reports alignment superelevation through a single domain tool. Use civil3d_superelevation_design_check for an explicit cross-slope limit check.", inputShape: { action: z.enum(["get", "set", "report"]), alignmentName: z.string().optional(), includeRawData: z.boolean().optional(), designSpeed: z.number().optional(), normalCrownSlope: z.number().optional(), attainmentMethod: z.enum(["AASHTO_2001", "AASHTO_2011", "manual"]).optional(), pivotPoint: z.enum(["centerline", "inside_edge", "outside_edge"]).optional(), outputPath: z.string().optional(), overwrite: z.boolean().optional(), includeRunoffTable: z.boolean().optional(), includeViolations: z.boolean().optional() }, supportedActions: ["get", "set", "report"], resolveAction: (rawArgs) => ({ action: String(rawArgs.action ?? ""), args: rawArgs }) },
    { toolName: "civil3d_superelevation_get", displayName: "Civil 3D Superelevation Get", description: "Gets alignment superelevation data.", inputShape: { alignmentName: z.string(), includeRawData: z.boolean().optional() }, supportedActions: ["get"], resolveAction: (rawArgs) => ({ action: "get", args: { action: "get", ...rawArgs } }) },
    { toolName: "civil3d_superelevation_set", displayName: "Civil 3D Superelevation Set", description: "Returns an explicit capability error because Civil 3D 2026 does not expose wizard calculation settings through the managed API.", inputShape: { alignmentName: z.string(), designSpeed: z.number().positive(), normalCrownSlope: z.number(), attainmentMethod: z.enum(["AASHTO_2001", "AASHTO_2011", "manual"]).optional(), pivotPoint: z.enum(["centerline", "inside_edge", "outside_edge"]).optional() }, supportedActions: ["set"], resolveAction: (rawArgs) => ({ action: "set", args: { action: "set", ...rawArgs } }) },
    { toolName: "civil3d_superelevation_design_check", displayName: "Civil 3D Superelevation Cross-Slope Check", description: "Checks calculated critical-station lane slopes against an explicit engineer-approved maximum; attainment/runoff verification is not inferred.", inputShape: { alignmentName: z.string(), designSpeed: z.number().positive(), maxSuperelevation: z.number().positive(), checkAttainmentLength: z.boolean().optional(), checkRunoffLength: z.boolean().optional() }, supportedActions: ["design_check"], resolveAction: (rawArgs) => ({ action: "design_check", args: { action: "design_check", ...rawArgs } }) },
    { toolName: "civil3d_superelevation_report", displayName: "Civil 3D Superelevation Data Report", description: "Exports calculated Civil 3D critical-station data without claiming standards compliance.", inputShape: { alignmentName: z.string(), outputPath: z.string().optional(), overwrite: z.boolean().optional(), includeRunoffTable: z.boolean().optional(), includeViolations: z.boolean().optional() }, supportedActions: ["report"], resolveAction: (rawArgs) => ({ action: "report", args: { action: "report", ...rawArgs } }) },
  ],
};
